### ISSUE TITLE
Publish plugin for SBT 1.x

### ISSUE THREAD

**Issue by n3ziniuka5** [scalajs-react-interface/sri#15]
The lack of sbt 1.x support means you cannot use this in a multi-project build, unless the whole project is on older sbt.

**Comment by frgomes** [comment]
I vote for SBT 1.x.

**Comment by frgomes** [comment]
@virtualirfan  @chandu0101:

Migrating ``sbt-sri-platform`` requires review of several other projects:

* http://github.com/frgomes/sri
* http://github.com/frgomes/sbt-sri-platform
* http://github.com/frgomes/sri-mobile.g8
* http://github.com/frgomes/sri-core
* http://github.com/frgomes/sri-mobile
* http://github.com/frgomes/sri-universal
* http://github.com/frgomes/sri-vector-icons
* http://github.com/frgomes/sri-navigation
* http://github.com/frgomes/sri-platform-config-android
* http://github.com/frgomes/sri-platform-config-ios
and also:
* https://github.com/frgomes/sjs-jest-core
* https://github.com/frgomes/sjs-plus-core

### Milestone 2018.10.0-M1

Update ``sbt-sri-platform``, ``mobile.g8`` and other projects:
- [ ] review build.sbt
- [ ] provide ``version.sbt`` and review interdependencies (from the light of ``sbt-dynver``)
- [ ] review project/plugins.sbt and project/build.properties
- [ ] review README
- [ ] review TODOs and FIXMEs
- [ ] cross compile 2.11, 2.12, 2.13
- [ ] make sure master of mobile.g8 works

**Comment by chandu0101** [comment]
> cross compile 2.10, 2.11, 2.12

why 2.10, 2.11 ? , let force community to move forward ..  , i'll vote 2.13 cross compile  

> provide version.sbt and review interdependencies (from the light of sbt-dynver

sbt-dynver is needed , it fetches version number from git tag in travis builds...

**Comment by frgomes** [comment]
@chandu0101 : I've cross compiled ``scalajs-jest/core`` and ``scalajs-plus/core`` on 2.11 and 2.12 already. Apparently it is OK but I'm not skilled enough on jest to tell for sure. I will cross compile to 2.13 as soon as dependencies are satisfied.

Yes, ``sbt-dynver`` is the way to go. However, at this point, it's easier for me to hardcode the version. After everything works as designed, I will focus only on making things fit well with tags and ``sbt-dynver``.
